export const ROUTER_MAP = {
    HOME: '/',
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    OPERATIONS: '/dashboard/operations',
    OPERATIONS_CREATE: '/dashboard/operations/create',
    OPERATIONS_EDIT: '/dashboard/operations/edit',
    WALLETS: '/dashboard/wallets',
    WALLETS_CREATE: '/dashboard/wallets/create',
    WALLETS_EDIT: '/dashboard/wallets/edit',
    WALLET_OPERATIONS: (id: string) => `/dashboard/wallets/${id}/operations`,
    WALLET_TYPES: '/dashboard/wallet-types',
    WALLET_TYPES_CREATE: '/dashboard/wallet-types/create',
    WALLET_TYPES_EDIT: '/dashboard/wallet-types/edit',
    GUIDES: '/dashboard/guides',
    GUIDES_CREATE: '/dashboard/guides/create',
    GUIDES_EDIT: '/dashboard/guides/edit',
    APPLICATIONS: '/dashboard/applications',
    APPLICATIONS_CREATE: '/dashboard/applications/create',
    APPLICATIONS_EDIT: '/dashboard/applications/edit',
    USERS: '/dashboard/users',
    USERS_CREATE: '/dashboard/users/create',
    CURRENCIES: '/dashboard/currencies',
    CURRENCIES_CREATE: '/dashboard/currencies/create',
    CURRENCIES_EDIT: '/dashboard/currencies/edit',
    NETWORKS: '/dashboard/networks',
    NETWORKS_CREATE: '/dashboard/networks/create',
    NETWORKS_EDIT: '/dashboard/networks/edit',
    NETWORK_TYPES: '/dashboard/network-types',
    NETWORK_TYPES_CREATE: '/dashboard/network-types/create',
    NETWORK_TYPES_EDIT: '/dashboard/network-types/edit',
    OPERATION_TYPES: '/dashboard/operation-types',
    OPERATION_TYPES_CREATE: '/dashboard/operation-types/create',
    OPERATION_TYPES_EDIT: '/dashboard/operation-types/edit',
    PLATFORMS: '/dashboard/platforms',
    PLATFORMS_CREATE: '/dashboard/platforms/create',
    PLATFORMS_EDIT: '/dashboard/platforms/edit',
    BANKS: '/dashboard/banks',
    BANKS_CREATE: '/dashboard/banks/create',
    BANKS_EDIT: '/dashboard/banks/edit',
    ADMIN: '/dashboard/admin',
    HELP: '/dashboard/help',
    FEEDBACK: '/dashboard/feedback',
    ANALYTICS: '/dashboard/analytics',
    REPORTS: '/dashboard/reports',
    CREATE_USER: '/dashboard/create',
    SETTINGS: '/dashboard/settings',
    ERROR: '/error',
};

export const ROUTER_TITLES: Record<string, string> = {
    [ROUTER_MAP.HOME]: 'MonteMove',
    [ROUTER_MAP.LOGIN]: 'Вход',
    [ROUTER_MAP.DASHBOARD]: 'Панель управления',
    [ROUTER_MAP.OPERATIONS]: 'Операции',
    [ROUTER_MAP.OPERATIONS_CREATE]: 'Создание',
    [ROUTER_MAP.OPERATIONS_EDIT]: 'Редактирование',
    [ROUTER_MAP.WALLETS]: 'Кошельки',
    [ROUTER_MAP.WALLETS_CREATE]: 'Создать кошелек',
    [ROUTER_MAP.WALLETS_EDIT]: 'Редактировать кошелек',
    '/dashboard/wallets/operations': 'История операций',
    [ROUTER_MAP.WALLET_TYPES]: 'Типы кошельков',
    [ROUTER_MAP.WALLET_TYPES_CREATE]: 'Создать тип кошелька',
    [ROUTER_MAP.WALLET_TYPES_EDIT]: 'Редактировать тип кошелька',
    [ROUTER_MAP.GUIDES]: 'Справочники',
    [ROUTER_MAP.GUIDES_CREATE]: 'Создание',
    [ROUTER_MAP.GUIDES_EDIT]: 'Редактирование',
    [ROUTER_MAP.APPLICATIONS]: 'Заявки',
    [ROUTER_MAP.APPLICATIONS_CREATE]: 'Создать заявку',
    [ROUTER_MAP.APPLICATIONS_EDIT]: 'Редактирование заявки',
    [ROUTER_MAP.USERS]: 'Пользователи',
    [ROUTER_MAP.USERS_CREATE]: 'Создать пользователя',
    [ROUTER_MAP.CURRENCIES]: 'Валюты',
    [ROUTER_MAP.CURRENCIES_CREATE]: 'Создать валюту',
    [ROUTER_MAP.CURRENCIES_EDIT]: 'Редактировать валюту',
    [ROUTER_MAP.NETWORKS]: 'Сети',
    [ROUTER_MAP.NETWORKS_CREATE]: 'Создать сеть',
    [ROUTER_MAP.NETWORKS_EDIT]: 'Редактировать сеть',
    [ROUTER_MAP.NETWORK_TYPES]: 'Типы сетей',
    [ROUTER_MAP.NETWORK_TYPES_CREATE]: 'Создать тип сети',
    [ROUTER_MAP.NETWORK_TYPES_EDIT]: 'Редактировать тип сети',
    [ROUTER_MAP.OPERATION_TYPES]: 'Типы операций',
    [ROUTER_MAP.OPERATION_TYPES_CREATE]: 'Создать тип операции',
    [ROUTER_MAP.OPERATION_TYPES_EDIT]: 'Редактировать тип операции',
    [ROUTER_MAP.PLATFORMS]: 'Платформы',
    [ROUTER_MAP.PLATFORMS_CREATE]: 'Создать платформу',
    [ROUTER_MAP.PLATFORMS_EDIT]: 'Редактировать платформу',
    [ROUTER_MAP.BANKS]: 'Банки',
    [ROUTER_MAP.BANKS_CREATE]: 'Создать банк',
    [ROUTER_MAP.BANKS_EDIT]: 'Редактировать банк',
    [ROUTER_MAP.ADMIN]: 'Блокировка периодов',
    [ROUTER_MAP.HELP]: 'Помощь',
    [ROUTER_MAP.FEEDBACK]: 'Обратная связь',
    [ROUTER_MAP.ANALYTICS]: 'Аналитика',
    [ROUTER_MAP.REPORTS]: 'Отчеты',
    [ROUTER_MAP.SETTINGS]: 'Настройки',
};
